apiVersion: apps/v1
kind: Deployment
metadata:
  name: $JAVA_APP
spec:
  selector:
    matchLabels:
      app: $JAVA_APP
  template:
    metadata:
      labels:
        app: $JAVA_APP
    spec:
      containers:
      - name: $JAVA_APP
        image: $DOCKER_REPO:$IMAGE_NAME
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: $JAVA_APP
spec:
  selector:
    app: $JAVA_APP
  ports:
  - port: 8080
    targetPort: 8080
